export const SERVICES = [
  {
    title: 'Oferte Speciale',
    description: 'Valabil pana la 30 iunie 2020',
    value: 'special_offers',
    hasCarousel: false,
    id: 'test',
    list: [
      {
        id: 'test-item',
        discount: '15',
        title: 'Masaj Suedez, clasic',
        time: '60 min',
        description: 'Introdu codul: 10OFF la checkout',
        price: 89,
      },
      {
        id: 'test-item-1',
        discount: '10',
        title: 'Coafat Special (2 p)',
        time: '60 min',
        description: 'Introdu codul: 10OFF la checkout',
        price: 89,
      },
      {
        id: 'test-item-2',
        discount: '10',
        title: 'Mani Pedi de Lux',
        time: '60 min',
        description: 'Introdu codul: 10OFF la checkout',
        price: 89,
      },
      {
        id: 'test-item-3',
        discount: '10',
        title: 'Mani Pedi (fara lac)',
        time: '60 min',
        description: 'Introdu codul: 10OFF la checkout',
        price: 89,
      },
    ],
  },
  {
    title: 'Masaj',
    description: null,
    value: 'masaj',
    hasCarousel: true,
    id: 'test-masaj',
    list: [
      {
        id: 'test-item',
        discount: '15',
        title: 'Masaj Suedez, clasic',
        time: '60 min',
        description: 'Introdu codul: 10OFF la checkout',
        price: 89,
      },
      {
        id: 'test-item-1',
        discount: '10',
        title: 'Coafat Special (2 p)',
        time: '60 min',
        description: 'Introdu codul: 10OFF la checkout',
        price: 89,
      },
      {
        id: 'test-item-2',
        discount: '10',
        title: 'Mani Pedi de Lux',
        time: '60 min',
        description: 'Introdu codul: 10OFF la checkout',
        price: 89,
      },
      {
        id: 'test-item-3',
        discount: '10',
        title: 'Mani Pedi (fara lac)',
        time: '60 min',
        description: 'Introdu codul: 10OFF la checkout',
        price: 89,
      },
      {
        id: 'test-item-4',
        discount: '10',
        title: 'Mani Pedi (fara lac)',
        time: '60 min',
        description: 'Introdu codul: 10OFF la checkout',
        price: 89,
      },
      {
        id: 'test-item-5',
        discount: '10',
        title: 'Mani Pedi (fara lac)',
        time: '60 min',
        description: 'Introdu codul: 10OFF la checkout',
        price: 89,
      },
    ],
  },
];
